import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Footer from '@/component/footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.top}>
          <Image className={styles.top_image} src="/top_image.jpg" layout='fill'
            objectFit='cover' alt="top image" priority={true} />
            <h1 className={styles.top_h1}>3b46 official site</h1>
        </div>
      </main>
      <Footer/>
    </>
  )
}
